Backend v2
session-foundation/session-staking-backend pull request #4
Opened 2024-11-20 06:30 UTC by Aerilym

https://gist.github.com/Aerilym/1a541dbb923498b04c89233293e02936

2025-03-18 23:31 UTC, Doy-lee requested changes

2025-03-18 23:31 UTC, Doy-lee commented on .gitmodules
> +	url = https://github.com/oxen-io/eth-sn-contracts.git
Can be updated to the `session-foundation` https://github.com/session-foundation/session-token-contracts

2025-03-18 23:31 UTC, Doy-lee commented on README.md
> +- **Api**: `api.py` is the main API server that handles most requests.
This doesn't seem relevant anymore file doesn't exist.

2025-03-18 23:31 UTC, Doy-lee commented on run_fetcher.py
> +import src.app_fetcher
I'd remove this file, I'm mindful of leaf files like these that are helper wrappers. `src.app_fetcher` is around ~6 lines of code and so we have a file which has an indirection to another file which runs the app, which then, indirects to the actual code. We can reduce these layers by just dropping it

```python
#!/usr/bin/env python3
from src import config
from src.staking.fetcher import App

app = App("fetcher")
app.run()
```

Having these leaf files is extra infrastructure that you have to ensure keeps working over time. I'd rather that the `README.md` just tell me to run the fetcher from the root directory by calling `python3 src/app_fetcher.py`

2025-03-18 23:31 UTC, Doy-lee commented on src/app_fetcher.py
> +from src import config
Unused

2025-03-18 23:31 UTC, Doy-lee commented on src/app_fetcher.py
> +app = App("fetcher")
So this pattern

```
if __name__ == "__main__":
    <run the app>
```

Is meant to handle the pattern you're doing here, where if you import `src/fetcher/app.py` it will not run the app but let you use `fetcher` as a library. But if you `python3 src/fetcher/fetcher.py` then it execute the branch.

In that sense I would encourage that we merge the entrypoint of the app into the app file itself for similar reasons that reducing the number of leaf functions cuts down on the number of files to juggle if there's not a strong reason to otherwise (and so forth for the other `app_<thing>.py` things you have).

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +class Backend:
Some of the configuration here seems overkill and not sure if some of these things are worth exposing. Especially if in the 99% case they are never going to be changed. The curse of having a lot of options is that there's a combinatoric explosion of behaviours that may be activated by misconfiguring the defaults which could subtly break the program in ways we didn't expect or degrade the performance of because the option wasn't exposed with consideration of its side effects on the rest of the program.

Not saying that is the case for all these options but we want to err towards designing systems that have defaults for the 99% case, and the 1% case should have to fork the system and or tweak the values themselves directly in the code because supporting those different scenarios unnecessarily doesn't warrant the extra complexity to reason about.

I'll add a review on the ones that feel sus.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    rpc_shared_cache:               int = 2
`rpc_shared_cache` is used in `staking/app.py` and the `staking/fetcher.py` but _only_ if they're not overridden by  `config.rpc_api_cache` and `config.backend.rpc_fetcher_cache` respectively so it has side effects that you have to go digging for, to simplify just anti-DRY, doesn't hurt to just explicitly set `rpc_api_cache = 2` and `rpc_fetcher_cache = 2`, so there's no tricky things going on behind your back that isn't obvious from the config file.

So I advocate for removing this. `rpc_fetcher_cache` is actually set to 1 below and `rpc_api_cache` is actually set to 2, so this value isn't actually being used at all.

Another thing is that, once enough different systems with different concerns rely on this, changing just this 1 value can have wide-ranging implications that at some point may be very difficult to reason about and so what ends up happening is that no one changes this number because they're worried about breaking production and instead introduce more variables to do a once-off change for the system they actually want to tweak.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    rpc_shared:               list[str] = ""
In the context that `rpc_shared` is used seems to only accept just a `str` if I'm not mistaken?

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    web3_provider_urls_eth:  list[str] = ["http://localhost:8545"]
Unused

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    rpc_api:                          str = ""
This seems to have the same issue as `rpc_shared_cache` and `rpc_api_cache` in that it overrides `rpc_shared`. I think we can get away with just `rpc_api`, but maybe to be clear we can rename this to `rpc_url` (and maybe have some comment to indicate you can use the `.sock` file or a `localhost`. 

Merge vars and simplify

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    rpc_api_cache:                    int = 2
I feel like this should just be hardcoded and only exposed if someone has a usecase to actually change it from 2 seconds. For us if 2 seconds doesn't suffice we'd just change the hardcoded value and lock it in.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    stale_time_seconds_contract_abis: int = 300
Logging interval, stale time seconds seems like something to hardcode and not expose and try aim for some sane defaults for the 99% usecase. We can re-expose it back out when something has a use-case.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    arbitrum_rescan_safety_blocks: int = 60
This one feels like something to hardcode. It's hard to see who would want to change this until someone has a use case for it to not be 60.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    refresh_rate_seconds_arbitrum: int = 10
Scan start chunk size and refresh rate also feels like they should be hardcoded. I think you have spent some time already to tune these to have fairly reasonable performance characteristics and we should trust that assumption, and remove them from being exposed publically and reduce cognitive overhead.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    ws_providers:            list[str] = []
The code currently only supports one provider. We should either document that, that the remaining URLs will be ignored and we plan to support it or change this to a string and update the usage code.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    # While it shouldn't be possible for this to happen, it is a safety measure.
I need you to talk me through this one because it sounds sus.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    ws_watch_token_events:        bool = False
Are we using this? Or can we drop this

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    sqlite_db_snapshot:                    str = "static/backend-snapshot.db"
Having just 1 snapshot seems sus since the thing updates every 10 minutes, it's a very small window to stop the whole system if the DB got corrupted before the snapshot is overwritten with the corrupted snapshot.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    coingecko_api_url:                  str = "https://api.coingecko.com/api"
Hmm, not sure if this should be configurable but instead hardcoded.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    prices_api_rate_limit_period:       int = 600
These two variables seem unused?

2025-03-18 23:31 UTC, Doy-lee commented on src/config_defaults.py
> +    web3_provider_urls:      list[str] = ["http://localhost:8545"]  # Default hardhat private chain node address)
Seems we only support 1 URL. We should either document that, that the remaining URLs will be ignored and we plan to support it or change this to a string and update the usage code.

2025-03-18 23:31 UTC, Doy-lee commented on src/config_validate.py
> +        assert is_not_empty_string(web3_provider_url), "web3_provider_urls is not set properly in config.py"
Inline `is_not_empty_string` into this for loop because we only use it once. We can pull it out to a common function if it gets used more than once, but otherwise it's good to resist that temptation because it's easy to try and make things available to be used generically in many situations but if we only actually use it once, it's less code and less overhead to just do it inline.

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/client.py
> +        caller_address: str | None,
Passing in the `caller` seems dubious because I'm not quite sure if there's any smart contract function that can be called that requires a caller without knowing their secret key to sign the transaction.

If the function takes _in_ an address, that function should take in an `address` at the call site. If a function is permissioned, then you need the secret key of the address to sign a transaction that calls that function. 

If you just need to call a read function on the contract then that doesn't need a specific wallet address to call the function, you can call those free-standing without needing any account or authorisation.

If all those assumptions are true then actually you wouldn't want to pass in the caller, just always rederive it from the secret key. This means we can drop all the error checking below on whether or not the caller address was correctly specified in the configuration file.

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/client.py
> +                raw_transaction = signed_tx.rawTransaction
Excellent

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/client.py
> +                raise ValueError("raw_transaction is None")
2x excellent, the hand we're dealt with.

2025-03-18 23:31 UTC, Doy-lee commented on src/db/read.py
> +        self.log.info(f"Connecting to db at {db_path}")
Move this down into the `connect` line since that's where it's actually connecting to the DB.

2025-03-18 23:31 UTC, Doy-lee commented on src/db/write.py
> +        self.log.info(f"Connecting to db at {db_path}")
Move down into the `connect` function

2025-03-18 23:31 UTC, Doy-lee commented on src/db/read.py
> +class DBReader:
The DB reader and DB writer are interesting helper classes but I don't think it's necessary to split them at this level because now features between them have to stay in sync. For example logging is available in the reader but not the writer (e.g. they have gone out of sync).

What they do, do is modify the `db_path` to invoke a particular loading behaviour for SQLite. This design is limiting because once you load the DB path say in read-only mode, you _really_ have to fight the design to load that same DB in write mode because now you have to remove the `file:` prefix and the `?mode=ro` suffix, to obtain the original DB path string.

It's essentially very rigid in a way that generates more code, (we have 2 classes, in 2 different files with different feature sets that have to be maintained and they also can't be converted into one another which means that the usage code has to additionally store the original db path in the surrounding context just incase that was the case).

I think these can be simplified down into 2 freestanding functions without a class

```
def sql_connect_in_read_mode(db_path: str):
    if not db_path.starts_with("...")
    ...
    return sqlite3.connect(final_db_path, uri=True)

def sql_connect_in_write_mode(db_path: str): # Maybe dubious, but perhaps good for API symmetry, I'll defer to you
    return sqlite3.connect(db_path, uri=True)
```

Now I see that these classes maybe want logging, we can keep the freestanding functions but have a class that is simply just the original `db_path` and the logger and the __init__ function initiates the logger. I'd advocate for considering the removal of the logger by verifying where it's being used and whether or not profiling should be a concern of the parent code context as we should aim to simplify.

There are some free-standing functions in `db/util.py` that operate in the same pattern I think we can simplify this class to.

2025-03-18 23:31 UTC, Doy-lee commented on src/log/perf.py
> +        elapsed_ms, elapsed_cpu_ms = self.end_timer(label)
Instead of `self.end_timer` we can call directly into `end_timer_enabled`. There's a bit of confusion here that potentially we could allow someone to change `self.end_timer` to point to something else but we can categorically rule that out by just calling the function directly so it's not ambiguous the behaviour of this call.

2025-03-18 23:31 UTC, Doy-lee commented on src/log/perf.py
> +    def __init__(self, logger: logging = None, enabled=True):
With logging in a performance context the overarching goal is to minimise any bookkeeping code running that is not the piece of code that you're trying to measure. In that manner this logging class when it runs in the hot path which is when times are measured and logs and emitted, if it's possible, we want to remove everything except recording of elapsed time. In the most minimal logger, that minimises the measuring of book-keeping code and maximises the measuring of sections of code we want to measure, what you want essentially boils down into 3 instructions (2 loads and a subtraction).

```
start = now()
<user code>
elapsed = now() - start
```

And then when you exit the section of code you want to record, you would then walk through the records and print the timings. This is what you'd want, from the perfect performance logger whose goal was to measure the execution time of everything between the start and end sections with minimal overhead.

That's the super overkill, super accurate version which we would want to aim for. So there are some suggestions we can make here to arrive to that

- Don't let logging be a `None` object. Assert that logger is set when enabled is true which means that you can remove the branch in `_log_end` that checks for the presence of the logger, it just assumes that it exists and that constructing a perf logger without it is an error state.

- Orphans seems to be a side-effect of mis-use of the performance logger, i.e. if you specify a label wrong the system gracefully handles this by eventually deleting it. This is a lot of extra work that is being executed in a performance sensitive context. For this we can replace it with an assert and crash very loudly when the logger is misused. 

I think it's better to crash loudly when that happens instead of somewhat silently handling it. This then means we can drop all the orphaning code because we assert that this class will be used correctly which means the perf logger is measuring more of the user's code than itself.

2025-03-18 23:31 UTC, Doy-lee commented on src/log/perf.py
> +        if start_time is not None and start_time_cpu is not None:
Assert that these are not `NONE`, i.e. prevent misuse of the logger, then, assume this code succeeds and so that ends up removing this branch.

If those are not none, then, this function will always return valid values which means all the code using this function does not have to branch on the result.

2025-03-18 23:31 UTC, Doy-lee commented on src/log/perf.py
> +        if elapsed_ms is not None and elapsed_cpu_ms is not None:
With the assert on `NONE`, then this branch also drops and _log_end now turns into a single call to the performance log message which then makes it obvious that this function doesn't need to be a function, you can just inline it to `end_enabled` which also additionally gets rid of function call overhead.

Printing to `stdout` in a performance sensitive context can really skew measurements of code by introducing unnecessary work. It's fairly problematic but I think for now we can leave it in and just take the wins we can get already from the previous suggested changes.

Removing it seems a bit more involved and I'd need to see more of how the perf logger is being used in the context of the entire program.

2025-03-18 23:31 UTC, Doy-lee commented on src/log/time_keeper.py
> +class TimeKeeper:
Interesting. The way this defers the logging of timings is the kind of pattern of usage that you'd want for a performance logging class. TimeKeeper is actually a performance logger

2025-03-18 23:31 UTC, Doy-lee commented on src/log/time_keeper.py
> +                self.logger.info("- More than one duration is required for duration stats")
We can get rid of this branch by setting `n_durations` to `1` in the potential divide by `0` in the `avg` calculation (can just use a ternary there to special case it). On face value I don't think those functions should fail if an empty list of durations is passed in. I might be wrong though.

In general it tends to work out better to have resilient code paths rather than branchy code paths that try to handle every failure because program output and behaviour becomes more predictable both for the readers of the code but also as a side effect, the CPU.

Similar in the `n_cpu_durations` section below.

2025-03-18 23:31 UTC, Doy-lee commented on src/log/time_keeper.py
> +            if len(cpu_durations) > 0:
`if n_cpu_durations > 0:`

2025-03-18 23:31 UTC, Doy-lee commented on src/config.py
> +
It's probably worth getting rid of all these examples. Just leave the top comment line with `# Local settings. Changes to this file ...` because they have all gone stale.

2025-03-18 23:31 UTC, Doy-lee commented on src/price/coingecko.py
> +    def format_for_db(self, response: dict, as_list: bool = True):
Is there a usecase for `as_list = False`? If not I'd advocate for deleting it.

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/util.py
> +    return block_number * 250
This is not guaranteed and hence misleading, as it's more like estimate the time elapsed for N blocks. I would inline this into the call-site with a disclaimer that this is a rough estimate since it's not guaranteed, putting it into a public API implies that it can be relied on by other people. Arbitrum produces blocks but only if there's transactions in the mempool. If there were none then it does not guarantee a block will be generated after 250ms.

Additionally since it's only used once in the entire codebase we should resist the urge to put extract it out and into the package interface as it adds bloat to the interface in what is actually just a inlinable one-liner.

2025-03-18 23:31 UTC, Doy-lee commented on src/oxen/omq.py
> +        if timeout is None:
Is this redundant with the timeout=1 as the default arg above? If that's the case I would just not allow timeout to not be none.

2025-03-18 23:31 UTC, Doy-lee commented on src/oxen/omq.py
> +        if self.json is None and self.future is not None:
Sufficient to just check `self.future is not None`

2025-03-18 23:31 UTC, Doy-lee commented on src/price/app.py
> +            if is_db_initialized(config.sqlite_db):
`if not`

2025-03-18 23:31 UTC, Doy-lee commented on src/price/app.py
> +    def get_price_for_token_cached(self, token: str, currency: str) -> PriceDB | None:
Having `currency` be specifiable is unusual. If I want USD and AUD, then I have to start two of these fetchers because a fetcher is only going to do one currency. 

But then in `get_token_price_info` we return the `usd` and `usd_market_cap` and we also only use the `default_currency` so I can't actually query the AUD value but I could if I go through the `get_price_for_token_uncached`, but the only API that calls that is the non-cached version but that _only_ uses the `app.config.default_currency`.

For the most part it doesn't seem like we properly support multi-currency and we may not have a usecase for this. It _might_ be useful for localisation but I'd suggest that we don't go down this route until we have a usecase for it. IME all crypto websites index assets by their USD price, I suggest we do that and remove the multi-currency support.

Keeps it simple, reduces code and complexity and we can reconsider adding it if a use-case arises.

2025-03-18 23:31 UTC, Doy-lee commented on src/price/app.py
> +        self.db_reader_prices = DBReaderPrices(
This pattern is a bit brittle, I still think we might be better off as free-standing functions. Since they all connect on demand, there's not much reason to encapsulate it behind the class. I think we can get away with my suggestion earlier to have a simple POD DB class that stores the DB path and (maybe the logger if it was useful to you).

Then having free functions like `get_latest_price` which then constructs a read-only string to open the DB and perform the operation, then disconnect from the DB after the function ends.

There's the question of what waste we're producing by constantly connecting and disconnecting from a SQL DB that I'm not very across. But there are incremental changes we can make to reduce code and simplify.

2025-03-18 23:31 UTC, Doy-lee commented on src/registration/app.py
> +    default_currency: str = None
Looks like copy-pasta from Coingecko price fetcher and is unused. Can be removed

2025-03-18 23:31 UTC, Doy-lee commented on src/registration/schema.sql
> +    timestamp FLOAT NOT NULL DEFAULT ((julianday('now') - 2440587.5)*86400.0), /* unix epoch */
`FLOAT` timestamp looks very sus. This should be int

2025-03-18 23:31 UTC, Doy-lee commented on src/registration/schema.sql
> +    sig_ed25519 BLOB NOT NULL,
I noticed that we don't write the contract address if it's present, is that an issue?

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/app.py
> +            if event.name == "NewServiceNodeContributionContract":
Can this branch trigger? We don't pass the NewSNContribContract name into `get_arbitrum_events`

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/app.py
> +    def get_network_info():
Empty response?

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/app.py
> +    def get_added_bls_keys():
The way this is figuring out the set of BLS keys is not going to scale with time since it's going to walk the entire history of the event list to figure it out.

Can this just use `get_nodes_cached()` and enumerate the BLS keys? That'll be a fairly consistent walk of around 1.5-2k entries.

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/app.py
> +    def get_contribution_contract_contributor_map_uncached():
I found this name quite confusing, not sure if it's just me. To clarify, this is finding all the contracts that a contributor has contributed to?

If that's true, maybe a more apt name is `get_contributor_to_multi_contrib_contracts_map`? This one is concerning in that reads the entire events DB then walks it all, this is also not going to scale with time, especially with a TTL of 1.

The scalability is related to the concern I wrote earlier but this may suffice for now. I guess this is for the historical view for a wallet. We'll need to store or have an acceleration structure at some point for this. I'd at least add a TODO here so that it's obvious that this needs to be improved.

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/app.py
> +            if eth_format(node.operator_address) == address:
These are ideally binary comparisons between the bytes. The reason for that is that constructing a checksum address from an address string means:

1. Converting the address back to binary
2. Hashing the address with keccak to get the hash
3. Converting the binary address back to hex
4. Walk through the hex and use the equivalent keccak hash's byte to determine if the character should be uppercased or lower cased
5. Compare the two hex strings together

There's a full round-trip involved just to check if the checksum address is valid as well as a keccak hash is expensive. On the other hand if you compare the bytes then:

1. Convert `address` to  bytes
2. Compare the `address` to `operator_address` bytewise (I believe operator_address is already in bytes)

And done. This is why you typically just want store addresses as bytes, and, only when you need to present the address to the user you convert at the UI boundary to a checksum address, or, if you're accepting input from the user you take in an address but immediately convert it back into binary for propagating through the system.

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/app.py
> +    @app.route("/contract/names")
What's the use case for the ABIs being public again?

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/app.py
> +    @app.route("/contract/addresses/core")
Use case?

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/app.py
> +    @app.route("/contract/contribution")
Use case? This is a pretty expensive call

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/app.py
> +            if not eth_wal or not eth_utils.is_address(eth_wal):
I don't think this is possible with the eth_wallet converter which uses the regex `eth_regex = "0x[0-9a-fA-F]{40}"`, if the eth wallet is non-compliant this route won't trigger

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/app.py
> +    def get_events_handler(count_limit=500, skip=0):
This makes me nervous. What's the usecase?

2025-03-18 23:31 UTC, Doy-lee commented on src/registration/read.py
> +                self.log.perf.end("get_registrations")
These nested perf markers is what would be causing the whole orphan situation in the logger which we should get rid of. These perf loggers seem like they're doing profiling of the duration of the function. 

You can still _have_ orphans because there's inevitably going be some due to Python using exceptions that unwind the stack (unless you wrapped everything in a try catch but that seem unergonomic to do so just for this).

What you do then is that when you start a performance logging scope you discard the last opened scope that was unclosed and restart the start time of the section.

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/fetcher.py
> +            init_db(config.backend.sqlite_db, config.backend.sqlite_schema)
This seems repeated enough that `init_db` should include the `if not is_db_initialized` bit into it and instead everyonce calls `init_db` which then idempotently handles doing a no-op if it's already initialised and if it isn't, initialised the DB.

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/fetcher.py
> +            else config.backend.rpc_shared_cache
Get rid of the shared override, is confusing.

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/fetcher.py
> +        self.db_writer = DBWriterStaking(
Same as all the other DB reader/writer patterns, pretty sure we can replace these abstractions with free-standing functions and reduce code.

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/fetcher.py
> +        generic_logger = Log(None)
How exactly does this work? I don't see it being used anywhere in the class

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/read.py
> +                cursor.execute("""SELECT address, beneficiary from service_nodes_contributions_staging ORDER BY fetched_block_height ASC""")
Does this execute not override the previous executed cursor results?

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/schema.sql
> +    timestamp FLOAT NOT NULL DEFAULT ((julianday('now') - 2440587.5)*86400.0), /* unix epoch */
Sus float timestamp

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/snapshot.py
> +        self.path_snapshot_tmp = snapshot_db_path + ".tmp"
So we only support 1 snapshot as I mentioned earlier. Whilst that is insufficient, how much space are we talking if we just backup the whole thing? 

I can appreciate the whole system but it's a lot of additional code. Can we get away with just using `sqlite3.Connection.backup` or even just at the file layer, a backup of all the SQL files into the DB? 

Part of the issue moving forward in the future is that maintainers may be tempted to add and remove tables from the backup process as the system requirements change and they're looking to save bytes and because the capability is there. They might end up doing that and inadvertently start creating backups that no-longer work and this might not be detected for awhile.

Doing a file level backup of the SQL DB is (I'm pretty sure) guaranteed to work given the current architecture since it seems we have pause and resume ability of monitoring the oxen and arbitrum chain. This is idiot-proof and is also the path of least resistance (a few syscalls vs the infrastructure setup here).

Additionally this leverages one of SQL's more important traits which is its ability to trivially be backed up by simplying copying the files. A per table read and extraction is usually the pain you have to go through with more managed DBs like postgres that is immediately sus that we have to do.

Can we trade off the extra storage size for simplicity here?

--

If we do file system level backups we should merge these into the process that's managing the DB. I believe atomicity of backup is lost by doing this. But if we take that simplified approach, I believe all of this can be encapsulated in free-standing function in the timer that periodically backs up the DB.

And if atomicity is an issue there, then `sqlite3.Connection.backup` should solve that instead of just copuing the DB files.

2025-03-18 23:31 UTC, Doy-lee commented on src/staking/snapshot.py
> +        self.path_snapshot_tmp = snapshot_db_path + ".tmp"
I'll also add, we should probably just timestamp these and store them, depends how big this gets but at worse maybe a rolling window of 2 years worth of snapshots.

2025-03-18 23:31 UTC, Doy-lee commented on src/util/cache.py
> +    def set_expiry_ttl(self, key: str, ttl: int):
Unused function can be removed

2025-03-18 23:31 UTC, Doy-lee commented on src/util/cache.py
> +        self.cache_expiry[key] = timestamp
Only used once AFAICT. Inline

2025-03-18 23:31 UTC, Doy-lee commented on src/util/cache.py
> +            return self.store.get(key)
It should be faster to change this around to

```python
if self.cache_expiry.get(key, 0) > now:
    result = self.store.get(key, None)
    if result is not None:
        return result
```

`key` in `self.store` my intuition says that should do a b-tree search for the key, then, `self.store.get` would do another b-tree search for the key that we now know exists.

2025-03-18 23:31 UTC, Doy-lee commented on src/util/config_import.py
> +def import_config():
This is only used in tests, I'd recommend inlining it into tests, it's a good idea to try and encapsulate test code to just tests as they usually break software patterns that can be confusing to have sitting in the repository in the general utilities folder.

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/abi_manager.py
> +        if file_name in self.cache:
This is really unusual that a loading function will have a cache? Is there a case where someone might call this more than once?

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/abi_manager.py
> +        if file_name in self.cache:
This is really unusual that a loading function will use the cache? Is there a case where someone might call this more than once?

It's surprising behaviour at a higher level from what someone would normally expect when you call a loading function on file paths.

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/abi_manager.py
> +        self.abi_dir = abi_dir
Hardcoding the ABI dir doesn't seem like the way to go for the reason that to change it means inspecting internals and overwriting it, but once you overwrite it `load_all_abis` now changes behaviour.

Passing the ABI dir is this thing that makes sense in the context of calling `load_all_abis`, it shouldn't be sticky and remain in memory. If you then update the DBs and call `load_all_abis` you'd expect the class to go reload the ABIs and not cache them.

To make it explicit I would imagine the ABI manager has a function that's like `load_abi_from_path` where you pass in an explicit path and it just loads and overwrites the ABI in the manager if it exists. Then you have `load_abi_from_dir` which loads all the `*.json` files and writes them in.

And I can call them as many times as I want, they won't cache and will always override the in-memory ones which is the most expected behaviour from a class like this. Locking in the ABI dir gets you into the situation where if you _wanted_ to change the directory its looking at, you now have this misconfigured object so now I need to go reinstantiate the object, run the constructor and load, then Python needs to go discard the old ABI manager.

It's just very brittle and not a very flexibly designed class that it requires a lot of work, programming wise but also CPU wise to do a simple operation like loading new ABIs from a given path.

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/contracts/service_node_contribution.py
> +        return "0x{:0128x}".format((pks[0] << 256) + pks[1])
Hmm .. what's the downshift for? Doesn't the contract just give you a tuple of 2x64 byte keys in a tuple (pk0, pk1)?

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/event_scanner.py
> +        # self.min_scan_chunk_size = 10  # 12 s/block = 120 seconds period
Duplicate line

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/event_scanner.py
> +        # self.chunk_size_increase = 2.0
Commented line

2025-03-18 23:31 UTC, Doy-lee commented on src/web3client/event_scanner.py
> +    def scan_chunk(self, start_block, end_block) -> Tuple[int, list]:
Will need you to walk me through the event scanner at some point to make sure I understand this

2025-03-18 23:54 UTC, Aerilym commented on src/db/read.py
> +class DBReader:
Yeah this is a very good point, I've remove the to db classes and just created a util function for connections in reading and writing modes as you suggested

2025-03-18 23:54 UTC, Aerilym commented on src/db/read.py
> +        self.log.info(f"Connecting to db at {db_path}")
deleted

2025-03-18 23:54 UTC, Aerilym commented on src/db/write.py
> +        self.log.info(f"Connecting to db at {db_path}")
deleted

2025-03-19 00:02 UTC, Aerilym commented on src/price/app.py
> +    def get_price_for_token_cached(self, token: str, currency: str) -> PriceDB | None:
This is true, we also havent made an endpoint for it, ill remove the half-baked feature

2025-03-19 03:03 UTC, Aerilym commented on src/price/coingecko.py
> +    def format_for_db(self, response: dict, as_list: bool = True):
deleted

2025-03-19 03:09 UTC, Aerilym commented on src/staking/app.py
> +    def get_network_info():
json_res adds the network info to every response

2025-03-19 03:10 UTC, Aerilym commented on src/staking/app.py
> +    def get_added_bls_keys():
this wouldnt account for nodes that are deregistered and awaiting liquidation right? this was supposed to be an alternative way than fetching the `bls key -> contractId` map from the sn rewards contract

2025-03-19 03:12 UTC, Aerilym commented on src/staking/app.py
> +    @app.route("/contract/contribution")
This is for getting the open contracts (status 0-2), should be limited to only ones with status <3. will fix that

2026-04-01 03:27 UTC, merged